config/routes.rb
Rails.application.routes.draw do
  get 'profile/edit'

  get 'logon/new'

  get  'signup' =>'user#new'
  post 'users' => 'user#create'
  get 'users/:id(.:format)' => 'user#show'
  get 'login' => 'logon#new'
  post 'login(.:format)' => 'logon#create' 
  get 'forgot' => 'logon#forgotpwd'
  post 'forgot(.:forgot)' => 'logon#sendpwd'
  get 'user/profile/edit' => 'profile#edit'

  resources :users
  resources :profiles

end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_one :profile
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/logon_controller.rb
class LogonController < ApplicationController
  def new
  end

  def create
  	user = User.find_by(email: params[:logon][:email].downcase)
    if user && user.authenticate(params[:logon][:password])
      render 'welcome'
    else
      render 'new'
    end
  end

  def welcome

  end

  def forgotpwd
  	
  end

  def sendpwd
  	user = User.find_by(email: params[:logon][:email].downcase)
  	# if user
  			
  	# else
  	# 	render 'new'
  	# end
  	render 'new' unless user
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
	def new
	end

	def create
	end

  def edit
  	@profile = Profile.find(params[:id])
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def new
  	@user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
  	@user = User.new(user_params)
  	if(@user.save)
      # @user.profile=
  		redirect_to @user
	  else
	  	render 'new'
	  end
  end

 private

  def user_params
    params.require(:user).permit(:name, :email, :password,:password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logon_helper.rb
module LogonHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AuthLogin</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/logon/forgotpwd.html.erb
<h2> Forgot your password </h2>

<div>
	<%= form_for(:logon, url: forgot_path) do |f| %>
		<%= f.label :email %>
  	<%= f.email_field :email %>

  	<%= f.submit "submit" %>
	<% end %>
</div>

app/views/logon/new.html.erb
<h1>Login to your account</h1>

<div>
	<%= form_for(:logon, url: login_path) do |f| %>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.submit "Log in" %>
    <% end %>

    <p>New user? <%= link_to "Sign up now!", signup_path %></p>
    <p> <%= link_to "Forgot password", forgot_path %></p>
</div>

app/views/logon/sendpwd.html.erb
<h2>Password sent to email.</h2>

app/views/logon/welcome.html.erb
<h2>Welcome</h2>

app/views/user/new.html.erb
<h1>Create new account</h1>

<div>
  <%= form_for(@user) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :email %>
    <%= f.email_field :email %>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.label :confirm_password %>
    <%= f.password_field :confirm_password %>

    <%= f.submit :signup %>
  <% end %>
</div>

app/views/user/show.html.erb
<h2>new user created <%= @user[:name] %></h2>